### ISSUE TITLE
Llama.Cpp has made changes.

### ISSUE THREAD

**Issue by 3Simplex** [rizitis/Quantizing_with_LlamaCpp#1]
Heads up:
Llama.Cpp has made some changes, I have updated the guide to reflect them.
In my case  ./quantize is now ./llama-quantize
and convert.py has moved and renamed to examples\convert-legacy-llama.py

The script they support now is the convert-hf-to-gguf.py which handles many model architectures as you will see in their readme.

**Comment by rizitis** [comment]
Before 2 weeks script was updated according to these llama updates. Plz read code.
Lines : 179,180,181
